# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_type', models.CharField(max_length=250)),
                ('furniture_for', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ItemName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.ItemCategory')),
            ],
        ),
    ]
