# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='furniture_for',
        ),
    ]
