# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-26 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160526_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null='TRUE'),
        ),
    ]
